### ISSUE TITLE
Convert Show Views to Blacklight Pages

### ISSUE THREAD

**Issue by tpendragon** [samvera/curation_concerns#749]
Right now we have our own show routes, when it seems like it'd make the most sense to use the configuration and features within Blacklight instead. Maybe this way we can get to a point where most concerns don't need a customized _attributes override, for instance.

**Comment by jcoyne** [comment]
This may require extending Blacklight to have a show page configuration per `display_type_field`, presently it only supports one configuration shared among all types of records. I'm thinking something like this:

```ruby
show_config_for 'Image' do
  config.add_show_field 'dimensions_ssm'
end
show_config_for 'Video' do
  config.add_show_field 'dimensions_ssm'
  config.add_show_field 'duration_ssm'
end

```

**Comment by tpendragon** [comment]
Old issue, but I was just reading it again: @cbeer how would you feel about a configuration feature like above for Blacklight?

**Comment by jcoyne** [comment]
This is already an open PR in Blacklight. I think we should do it

**Comment by tpendragon** [comment]
Talking about https://github.com/projectblacklight/blacklight/pull/1417/files ?

**Comment by jcoyne** [comment]
Yep

**Comment by mjgiarlo** [comment]
@jcoyne @tpendragon Should we take this up in Hyrax?

**Comment by jcoyne** [comment]
Yes, but it will depend on Blacklight 7 so it's a ways off

**Comment by mjgiarlo** [comment]
Moved to Hyrax.
